##spring.application.name=club-villa-elvira

##spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
##spring.datasource.username=${DB_USER}
##spring.datasource.password=${DB_PASSWORD}
##spring.datasource.driver-class-name=org.postgresql.Driver

# Dialecto de Hibernate para Postgres
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
##spring.jpa.hibernate.ddl-auto=update


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username={MAIL}
spring.mail.password={PASSWORD_MAIL}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Mail de envios
app.url.mail=${APP_BASE_URL}/reset-password?token=
app.mail.from=${MAIL}
app.reset.token..minutes=15

# Logging de la aplicacion
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.boot.autoconfigure.mail=DEBUG
logging.level.com.sun.mail=DEBUG

springdoc.override-with-generic-response=false

server.port=${PORT}
