spring.application.name=login

spring.datasource.url=jdbc:postgresql://localhost:5432/club
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialecto de Hibernate para Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=DEBUG

# SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=guidoferrari24@gmail.com
spring.mail.password=wygxliakoxltibbb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Mail de envios
app.url.mail=http://localhost:8080/reset-password?token=
app.mail.from=guidoferrari24@gmail.com
app.reset.token..minutes=15

# Logging de la aplicacion
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.boot.autoconfigure.mail=DEBUG
logging.level.com.sun.mail=DEBUG

springdoc.override-with-generic-response=false

server.port=8081
